### PR TITLE
Connection speedUp

### PR DESCRIPTION
**Pull request by Bighoneypot**
Connection speedUp

### CODE REVIEW

**Comment by sborsay** [comment]
Hi,

I'll consider it but I don't want to complicate the sketch by adding another library (#include "sntp.h") when the current sketch hasn't had any complaints relevant to the x509 getting timestamped through the time server and causing a delay.

**Comment by Bighoneypot** [comment]
Hello, the library is part of the esp8266 and therefore it is not necessary to install other libraries. Some users have encountered this problem. If you enter this you do not create any complications, but add strength and speed to the code, especially when used in the eu. I hope you can fulfill my request.

**Comment by sborsay** [comment]
Ok I will test the change out and get some performance metrics sometime this week and let you know the results.

**Comment by Bighoneypot** [comment]
Ok, thanks 👍🏻for the update

**Comment by sborsay** [comment]
Added SNTP to help speed up time fetch from certain areas like Euro zones according to: 
https://github.com/Bighoneypot

I tested the change and didn't affect performance adversely so squashed and merged.

**Comment by sborsay** [comment]
I merged the change although I didn't see any difference, the program still
ran ok.  thanks

sdb

**Pull request merged**
